fix: undefined function call in error_function()

diff --git a/makedeb b/makedeb
--- a/makedeb
+++ b/makedeb
@@ -282,10 +282,10 @@ function decompress_source_file {
 error_function() {
     # first exit all subshells, then print the error
     if (( ! BASH_SUBSHELL )); then
-        error "A failure occurred in %s()." "$1"
-        plainerr "$(gettext "Aborting...")"
+        err "A failure occurred in %s()." "$1"
+        err "$(gettext "Aborting...")"
     fi
-    exit $E_USER_FUNCTION_FAILED
+    exit 1
 }
 
 # use less strict shell for custom functions
